# Generated by Django 5.1.4 on 2025-04-07 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACC', 'ACCEPTED'), ('PEN', 'PENDING'), ('BLK', 'BLOCKED')], default='PEN', max_length=3)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_request', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default='0', max_length=10)),
                ('level', models.FloatField(default=0.0)),
                ('rank', models.CharField(default='default', max_length=20)),
                ('game_mode', models.CharField(max_length=20)),
                ('super_user', models.CharField(max_length=20)),
                ('winner', models.CharField(max_length=20)),
                ('loser', models.CharField(max_length=20)),
                ('wins', models.CharField(default='0', max_length=20)),
                ('losses', models.CharField(default='0', max_length=20)),
                ('mainUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_user_pm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
